---
ansible-navigator:
  ansible:
    inventory:
      entries:
      - /home/student/ex457_work/inventory
  execution-environment:
    container-engine: podman
    enabled: true
    image: hub.lab.example.com/ee-supported-rhel8:latest
    pull:
      policy: missing
  mode: stdout
  playbook-artifact:
    enable: false
